# Generated by Django 4.1.4 on 2023-04-16 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.server'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 23, 16, 30, 3295)),
        ),
    ]
